services:
  customer-service:
    build: ./customer-service
    ports:
      - "8081:8080"
  account-service:
    build: ./account-service
    ports:
      - "8082:8080"
  transaction-service:
    build: ./transaction-service
    ports:
      - "8083:8080"
