version: '3.8'

services:
  customer-service:
    build: ./customer-service
    ports:
      - "8081:8081"
    depends_on:
      - customer-db
    environment:
      SPRING_PROFILES_ACTIVE: default

  account-service:
    build: ./account-service
    ports:
      - "8082:8082"
    depends_on:
      - customer-db
    environment:
      SPRING_PROFILES_ACTIVE: default

  transaction-service:
    build: ./transaction-service
    ports:
      - "8083:8083"
    depends_on:
      - customer-db
    environment:
      SPRING_PROFILES_ACTIVE: default

  customer-db:
    image: postgres:15
    container_name: customer-db
    restart: always
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  account-db:
    image: postgres:15
    container_name: account-db
    environment:
      POSTGRES_DB: accountdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    restart: always